#ifndef RECOVERY_ERRORCODE_H
#define RECOVERY_ERRORCODE_H

enum KaiErrorCode {
  RECOVERY_FILEMOUNT_FAILURE = 3013,
  RECOVERY_FILEMAP_FAILURE     /*3014*/,
  RECOVERY_KEYLOADED_FAILURE   /*3015*/,
  RECOVERY_BINARY_FAILURE      /*3016*/,
  RECOVERY_PARTITIONWRITE_FAILURE /*3017*/,
  RECOVERY_FILECREATE_FAILURE  /*3018*/,
  RECOVERY_FILECOPY_FAILURE    /*3019*/,
  RECOVERY_BATTERY_LOW         /*3020*/,
  RECOVERY_ZIPVERIFIED_FAILURE /*3021*/,
  RECOVERY_ZIPOPENED_FAILURE   /*3022*/,

/*Already defined in diff tools*/
  UPDATER_CACHE_NOT_ENOUGH = 3306,

  UPDATER_STAT_FAILURE = 3400,
  UPDATER_MKDIR_FAILURE                    /*3401*/,
  UPDATER_BLOC_FILENAME_TYPE_NOT_STR       /*3402*/,
  UPDATER_BLOC_TRANSFER_LIST_TYPE_NOT_BLOB /*3403*/,
  UPDATER_FILE_OPEN_FAILURE                /*3404*/,
  UPDATER_FILE_SEEK_FAILURE                /*3405*/,
  UPDATER_FILE_READ_FAILURE                /*3406*/,
  UPDATER_BLOC_THREAD_CREATE_FAILURE       /*3407*/,
  UPDATER_MEMORY_ALLOC_FAILURE             /*3408*/,
  UPDATER_BLOC_COUNT_UNEXPECTED            /*3409*/,
  UPDATER_BLOC_MAX_STASH_UNEXPECTED        /*3410*/,
  UPDATER_BLOC_COMMAND_EXECUTE_FAILURE     /*3411*/,
  UPDATER_ARGS_COUNT_UNEXPECTED            /*3412*/,
  UPDATER_ARGS_READ_FAILURE                /*3413*/,
  UPDATER_TUNE_TO_FS_FAILURE               /*3414*/,
  UPDATER_MOUNT_POINT_ARGS_EMPTY           /*3415*/,
  UPDATER_FORMAT_ARGS_EMPTY                /*3416*/,
  UPDATER_RENAME_ARGS_EMPTY                /*3417*/,
  UPDATER_MERGE_ARGS_EMPTY                 /*3418*/,
  UPDATER_RENAME_CREATE_PARENTS_FAILURE    /*3419*/,
  UPDATER_RENAME_FAILURE                   /*3420*/,
  UPDATER_SYS_LINK_FAILURE                 /*3421*/,
  UPDATER_LSTAT_FAILURE                    /*3422*/,
  UPDATER_SET_META_FAILURE                 /*3423*/,
  UPDATER_DEVICE_UNCOMPATIBLE              /*3424*/,
  UPDATER_EXCEED_FILE_GETPROP_SIZE         /*3425*/,
  UPDATER_WRITE_RAW_IMAGE_ARGS_ERROR       /*3426*/,
  UPDATER_NUM_PARSED_FAILURE               /*3427*/,
  UPDATER_SHA1_NOT_STR                     /*3428*/,
  UPDATER_PATCH_NOT_BLOB                   /*3429*/,
  UPDATER_REBOOT_FAILURE                   /*3430*/,
  UPDATER_FILE_COPY_ARGS_ERROR             /*3431*/,
  UPDATER_FILE_COPY_FAILURE                /*3432*/,
};

#endif
